apiVersion: apps/v1
kind: Deployment
metadata:
  name: task9-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task9
  template:
    metadata:
      labels:
        app: task9
    spec:
      containers:
      - name: task9
        image: chandrakanth00/task9:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: uri